# Generated by Django 3.2.23 on 2024-01-17 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='name',
        ),
    ]
